(in-package #:cl-tls-kit/test)

(defun run-client-tests ()
  (let* ((reads 0) (writes nil) (events nil) (secrets nil) (close-calls 0)
        (provider (lambda (client input)
                    (declare (ignore client))
                    (push input events)
                    (if (eq input :start)
                        '(:state :awaiting-input)
                        '(:state :connected :alpn "h2")))))
    (let ((client (tls-kit::make-tls-client
                   :transport-read (lambda (client) (declare (ignore client)) (incf reads) #(1 2))
                   :transport-write (lambda (client bytes) (declare (ignore client)) (push bytes writes))
                   :provider (list :handshake provider
                                   :close-notify
                                   (lambda (client)
                                     (declare (ignore client))
                                     (incf close-calls)
                                     #(1 0)))
                   :record-protect (lambda (client bytes) (declare (ignore client)) (vector 9 (aref bytes 0)))
                   :record-unprotect (lambda (client bytes) (declare (ignore client)) (aref bytes 0))
                   :quic-message-callback (lambda (client message) (declare (ignore client)) (push message events))
                   :quic-secret-callback (lambda (client level direction secret)
                                           (declare (ignore client))
                                           (push (list level direction secret) secrets)))))
      (check (eq (tls-kit::tls-client-state client) :new) "client starts new")
      (check (handler-case (progn (tls-kit::tls-client-read client) nil)
               (tls-kit::tls-client-state-error () t)) "read before handshake is rejected")
      (tls-kit::tls-client-start client)
      (check (eq (tls-kit::tls-client-state client) :awaiting-server) "provider controls handshake state")
      (check (handler-case (progn (tls-kit::tls-client-step client '(:type :encrypted-extensions)) nil)
               (tls-kit::unexpected-message () t)) "unexpected message is rejected")
      (tls-kit::tls-client-step client '(:type :server-hello))
      (check (eq (tls-kit::tls-client-state client) :connected) "only provider result connects")
      (check (string= (tls-kit::tls-client-alpn client) "h2") "ALPN is provider result")
      (check (= (tls-kit::tls-client-read client) 1) "read crosses record boundary")
      (tls-kit::tls-client-write client #(7))
      (check (equalp (first writes) #(9 7)) "write crosses record boundary")
      (tls-kit::tls-client-emit-quic-message client :crypto)
      (tls-kit::tls-client-emit-quic-secret client :handshake :write #(3))
      (check (= reads 1) "transport read called once")
      (check (equalp (first secrets) '(:handshake :write #(3))) "QUIC secret callback boundary")
      (tls-kit::tls-client-close client)
      (check (eq (tls-kit::tls-client-state client) :closed) "close transitions state")
      (check (= close-calls 1) "provider creates close_notify once")
      (check (equalp (first writes) #(1 0)) "close_notify crosses the transport boundary")
      (tls-kit::tls-client-close client)
      (check (= close-calls 1) "repeated close does not resend close_notify")))
  (let ((client (tls-kit::make-tls-client)))
    (check (handler-case (progn (tls-kit::tls-client-check-server-random
                                client #(0 0 0 0 0 0 0 68 79 87 78 71 82 68 1)) nil)
             (tls-kit::tls12-downgrade-sentinel () t)) "TLS 1.2 downgrade sentinel is rejected")
    (check (handler-case (progn (tls-kit::tls-client-start client) nil)
             (tls-kit::tls-client-state-error () t)) "missing provider is rejected"))
  (let ((client (tls-kit::make-tls-client
                 :provider (list :handshake
                                 (lambda (client input)
                                   (declare (ignore client input))
                                   '(:state :connected :peer-certificate :leaf)))
                 :verify-certificate (lambda (certificate)
                                       (declare (ignore certificate))
                                       nil))))
    (check (handler-case (progn (tls-kit::tls-client-start client) nil)
             (tls-kit::tls-client-verification-error () t))
           "verification failure is a client condition"))
  t)
