(in-package #:cl-tls-kit/test)

(unless (fboundp 'check)
  (defun check (condition message)
    (unless condition (error "Handshake test failed: ~A" message))))

(defun run-handshake-tests ()
  (let* ((random (make-array 32 :element-type '(unsigned-byte 8) :initial-element 7))
         (hello (make-tls13-client-hello
                 #x0303 random #(1 2) #( #x1301 #x1302)
                 (list (make-tls-extension 43 #(2 3 4  )))))
         (wire (encode-client-hello hello))
         (decoded (decode-client-hello wire)))
    (check (equalp random (tls13-client-hello-random decoded))
           "ClientHello random round trip")
    (check (equalp #( #x1301 #x1302) (tls13-client-hello-cipher-suites decoded))
           "ClientHello cipher suites round trip")
    (check (handler-case (progn (decode-client-hello (subseq wire 0 (1- (length wire)))) nil)
             (tls13-decode-error () t))
           "truncated ClientHello is rejected")
    (check (equalp
            (tls13-certificate-verify-input :client #(#x01))
            (concatenate '(vector (unsigned-byte 8))
                         (make-array 64 :element-type '(unsigned-byte 8)
                                     :initial-element #x20)
                         #(84 76 83 32 49 46 51 44 32 99 108 105 101 110 116
                           32 67 101 114 116 105 102 105 99 97 116 101 86 101 114
                           105 102 121)
                         #(0)
                         #(#x01)))
           "CertificateVerify context input")
    (let* ((server (make-tls13-server-hello
                    #x0303 (make-array 32 :element-type '(unsigned-byte 8) :initial-element 8)
                    #(1 2) #x1301 (list (make-tls-extension 43 #(2 3 4)))))
           (encrypted (make-tls13-encrypted-extensions
                       (list (make-tls-extension 10 #()))))
           (certificate (make-tls13-certificate
                         #() (list (make-tls13-certificate-entry
                                    #(1 2 3) (list (make-tls-extension 10 #()))))))
           (verify (make-tls13-certificate-verify #x0804 #(9 8 7)))
           (finished (make-tls13-finished #(1 2 3 4)))
           (ticket (make-tls13-new-session-ticket 10 #(1 2) #(3 4)
                                                   (list (make-tls-extension 42 #())) 17))
           (update (make-tls13-key-update 1))
           (request (make-tls13-certificate-request #()
                                                    (list (make-tls-extension 13 #(0 2 #x04 #x03))))))
      (check (typep (decode-server-hello (encode-server-hello server)) 'tls13-server-hello)
             "ServerHello round trip")
      (check (typep (decode-encrypted-extensions (encode-encrypted-extensions encrypted))
                    'tls13-encrypted-extensions)
             "EncryptedExtensions round trip")
      (check (typep (decode-certificate (encode-certificate certificate)) 'tls13-certificate)
             "Certificate round trip")
      (check (typep (decode-certificate-verify (encode-certificate-verify verify))
                    'tls13-certificate-verify)
             "CertificateVerify round trip")
      (check (equalp (encode-finished (decode-finished (encode-finished finished))) #(1 2 3 4))
             "Finished round trip")
      (check (typep (decode-new-session-ticket (encode-new-session-ticket ticket))
                    'tls13-new-session-ticket)
             "NewSessionTicket round trip")
      (check (= (cl-tls-kit::tls13-new-session-ticket-ticket-age-add
                 (decode-new-session-ticket (encode-new-session-ticket ticket))) 17)
             "NewSessionTicket ticket_age_add round trip")
      (check (= (cl-tls-kit::tls13-key-update-request
                 (decode-key-update (encode-key-update update))) 1)
             "KeyUpdate round trip")
      (check (typep (decode-certificate-request (encode-certificate-request request))
                    'tls13-certificate-request)
             "CertificateRequest round trip")
      (check (typep (decode-handshake (encode-handshake 24 update)) 'tls13-key-update)
             "framed KeyUpdate round trip")
      (check (handler-case
                 (progn (decode-encrypted-extensions #(0 8 0 1 10 0 1 10)) nil)
                 (tls13-decode-error () t))
             "duplicate extensions are rejected")
      (check (handler-case
                 (progn (decode-key-update #(2)) nil)
                 (tls13-decode-error () t))
             "invalid KeyUpdate request is rejected"))
    (let ((state (make-tls13-state :client)))
      (tls13-state-advance state 2)
      (check (eq (tls13-state-phase state) :server-hello)
             "state accepts ServerHello")
      (check (handler-case (progn (tls13-state-advance state 1) nil)
               (tls13-state-error () t))
             "state rejects an unexpected message"))
    t))
