(in-package #:cl-tls-kit/test)

(defun record-test-check (condition message)
  (unless condition (error "Record test failed: ~A" message)))

(defun %record-provider ()
  (and (find-package '#:crypto-kit)
       (make-cl-crypto-kit-provider)))

(defun %record-tamper (wire)
  (let ((copy (copy-seq wire)))
    (setf (aref copy (1- (length copy)))
          (logxor (aref copy (1- (length copy))) 1))
    copy))

(defun run-record-tests ()
  (let* ((payload #(1 2 3))
         (plain (make-tls-plaintext 23 payload))
         (encoded (encode-tls-plaintext plain))
         (iv (make-array 12 :element-type '(unsigned-byte 8) :initial-element 0))
         (nonce (tls-record-nonce iv 1))
         (aad (tls-record-additional-data 23 9)))
    (record-test-check (= (length encoded) 8) "TLSPlaintext header and fragment")
    (record-test-check (equalp (tls-plaintext-fragment (decode-tls-plaintext encoded)) payload)
                       "TLSPlaintext round trip")
    (record-test-check (= (aref nonce 11) 1) "sequence XOR IV")
    (record-test-check (equalp aad #(23 3 3 0 9)) "additional_data")
    (let ((seen-aad nil))
      (multiple-value-bind (wire next)
          (encrypt-tls-record plain :key iv 0
                              (lambda (key nonce input additional-data)
                                (declare (ignore key nonce))
                                (setf seen-aad additional-data)
                                (concatenate '(vector (unsigned-byte 8))
                                             input #(170 85)))
                              :padding-length 2 :tag-length 2)
        (record-test-check (= next 1) "sequence increments after encryption")
        (record-test-check (equalp seen-aad #(23 3 3 0 8))
                           "provider receives TLSCiphertext additional_data")
        (multiple-value-bind (decoded decrypt-next)
            (decrypt-tls-record
             wire :key iv 0
             (lambda (key nonce ciphertext additional-data)
               (declare (ignore key nonce additional-data))
               (subseq ciphertext 0 (- (length ciphertext) 2)))
             :tag-length 2)
          (record-test-check (= decrypt-next 1) "sequence increments after decryption")
          (record-test-check (equalp (tls-plaintext-fragment decoded) payload)
                             "encrypted padding is removed")
          (record-test-check (= (tls-plaintext-content-type decoded) 23)
                             "inner content type is restored"))))
    (record-test-check
     (handler-case (progn (make-tls-plaintext 23 (make-array 16385 :element-type '(unsigned-byte 8))) nil)
       (tls-record-overflow () t))
     "2^14 plaintext limit")
    (record-test-check
     (handler-case (progn (decode-tls-plaintext #(23 3 3 0 1)) nil)
       (tls-invalid-record () t))
     "truncated fragment")
    (record-test-check
     (handler-case (progn (make-tls-plaintext 22 #()) nil)
       (tls-invalid-record () t))
     "empty handshake fragment is rejected")
    (record-test-check
     (handler-case (progn (make-tls-plaintext 21 #()) nil)
       (tls-invalid-record () t))
     "empty alert fragment is rejected")
    (record-test-check (tls-key-update-p
                        (make-tls-plaintext 22 #(24 0 0 1 0)))
                       "KeyUpdate format")
    (record-test-check (tls-close-notify-p
                        (make-tls-plaintext 21 #(1 0)))
                       "close_notify format")
    (record-test-check (not (tls-close-notify-p
                             (make-tls-plaintext 21 #(2 0))))
                       "reject fatal close_notify shape")
    (record-test-check (not (tls-close-notify-p
                             (make-tls-plaintext 21 #(1 0 0))))
                       "reject padded close_notify shape")
    (let ((provider (%record-provider)))
      (when provider
        (dolist (algorithm '(:aes-128-gcm :chacha20-poly1305))
          (let* ((key-length (if (eq algorithm :chacha20-poly1305) 32 16))
                 (secret (make-array 32 :element-type '(unsigned-byte 8)
                                     :initial-element #x5a))
                 (sender (cl-tls-kit::make-tls13-traffic-state provider :sha256 algorithm
                                                              secret key-length 12))
                 (receiver (cl-tls-kit::make-tls13-traffic-state provider :sha256 algorithm
                                                                secret key-length 12))
                 (plain (make-tls-plaintext 23 #(9 8 7 6))))
            (multiple-value-bind (wire ignored)
                (cl-tls-kit::encrypt-tls13-traffic-record plain sender)
              (declare (ignore ignored))
              (multiple-value-bind (decoded ignored)
                  (cl-tls-kit::decrypt-tls13-traffic-record wire receiver)
                (declare (ignore ignored))
                (record-test-check (equalp (tls-plaintext-fragment decoded)
                                           #(9 8 7 6))
                                   "real AEAD round trip"))
              (record-test-check
               (handler-case
                   (progn (cl-tls-kit::decrypt-tls13-traffic-record (%record-tamper wire) receiver)
                          nil)
                 (tls-aead-error () t)
                 (tls-invalid-record () t))
               "real AEAD rejects tampering")
              (record-test-check (= (cl-tls-kit::tls13-traffic-state-sequence-number receiver) 1)
                                 "failed authentication does not advance sequence")
              (cl-tls-kit::tls13-update-traffic-secret sender)
              (cl-tls-kit::tls13-update-traffic-secret receiver)
              (record-test-check
               (handler-case
                   (progn (cl-tls-kit::decrypt-tls13-traffic-record wire receiver) nil)
                 (tls-aead-error () t)
                 (tls-invalid-record () t))
               "updated traffic keys reject old ciphertext")
              (multiple-value-bind (updated-wire ignored)
                  (cl-tls-kit::encrypt-tls13-traffic-record plain sender)
                (declare (ignore ignored))
                (multiple-value-bind (decoded ignored)
                    (cl-tls-kit::decrypt-tls13-traffic-record updated-wire receiver)
                  (declare (ignore ignored))
                  (record-test-check (equalp (tls-plaintext-fragment decoded)
                                             #(9 8 7 6))
                                     "updated traffic keys interoperate")
                  (record-test-check (= (cl-tls-kit::tls13-traffic-state-sequence-number receiver) 1)
                                     "KeyUpdate starts a fresh sequence"))))))))
    t))
