(in-package #:cl-tls-kit)

(define-condition der-error (error)
  ((message :initarg :message :reader der-error-message)
   (offset :initarg :offset :initform nil :reader der-error-offset))
  (:report (lambda (condition stream)
             (format stream "DER error~@[ at octet ~D~]: ~A"
                     (der-error-offset condition)
                     (der-error-message condition)))))

(defstruct (der-node (:constructor %make-der-node (tag constructed-p value children)))
  (tag 0 :type (unsigned-byte 32))
  (constructed-p nil :type boolean)
  value
  children)

(defun make-der-node (&key tag constructed-p value children)
  (check-type tag (unsigned-byte 32))
  (when (and constructed-p (null children)) (setf children '()))
  (%make-der-node tag (not (null constructed-p)) value children))

(defun %der-fail (message offset)
  (error 'der-error :message message :offset offset))

(defun %octets (value)
  (cond ((and (vectorp value) (every (lambda (byte) (typep byte '(unsigned-byte 8))) value))
         (coerce value '(vector (unsigned-byte 8))))
        ((listp value) (coerce value '(vector (unsigned-byte 8))))
        (t (error 'type-error :datum value :expected-type '(vector (unsigned-byte 8))))))

(defun %encode-length (length)
  (if (< length 128)
      (vector length)
      (let ((digits '()) (n length))
        (loop while (> n 0) do (push (logand n #xff) digits) (setf n (ash n -8)))
        (coerce (cons (+ #x80 (length digits)) digits) '(vector (unsigned-byte 8))))))

(defun %encode-tag (tag constructed-p)
  (let ((class-bits (ash (ldb (byte 2 24) tag) 6))
        (number (logand tag #x1fffffff)))
    (when (>= number #x1f)
      (let ((out (list (logior class-bits (if constructed-p #x20 0) #x1f)))
            (parts '()) (n number))
        (loop do (push (logand n #x7f) parts) (setf n (ash n -7)) while (> n 0))
        (loop for part in parts do (push (if (eq part (car (last parts))) part (logior part #x80)) out))
        (return-from %encode-tag (coerce (nreverse out) '(vector (unsigned-byte 8))))))
    (vector (logior class-bits (if constructed-p #x20 0) number))))

(defun der-encode (node)
  (check-type node der-node)
  (let* ((constructed (der-node-constructed-p node))
         (content (if constructed
                      (apply #'concatenate '(vector (unsigned-byte 8))
                             (mapcar #'der-encode (der-node-children node)))
                      (%octets (der-node-value node))))
         (tag (%encode-tag (der-node-tag node) constructed))
         (length (%encode-length (length content))))
    (concatenate '(vector (unsigned-byte 8)) tag length content)))

(defun encode-der (node) (der-encode node))

(defun %read-length (bytes pos)
  (when (>= pos (length bytes)) (%der-fail "missing length" pos))
  (let ((first (aref bytes pos)))
    (cond ((< first 128) (values first (1+ pos)))
          ((= first #x80) (%der-fail "indefinite length is not valid DER" pos))
          (t (let ((count (logand first #x7f)))
               (when (or (= count 0) (> count 4)) (%der-fail "invalid length encoding" pos))
               (when (> (+ pos count) (length bytes)) (%der-fail "truncated length" pos))
               (when (zerop (aref bytes (1+ pos))) (%der-fail "non-minimal length" pos))
               (let ((n 0))
                 (dotimes (i count)
                   (setf n (+ (ash n 8) (aref bytes (+ 1 pos i)))))
                 (when (< n 128) (%der-fail "long-form length used for short value" pos))
                 (values n (+ pos count 1))))))))

(defun %read-tag (bytes pos)
  (when (>= pos (length bytes)) (%der-fail "missing tag" pos))
  (let* ((first (aref bytes pos)) (class (logand first #xc0))
         (constructed (not (zerop (logand first #x20))))
         (number (logand first #x1f)) (next (1+ pos)))
    (if (/= number #x1f)
        (values (logior (ash class 24) number) constructed next)
        (progn
          (when (>= next (length bytes)) (%der-fail "truncated high-tag-number" pos))
          (when (zerop (logand (aref bytes next) #x7f)) (%der-fail "non-minimal tag" next))
          (setf number 0)
          (loop
            (when (>= next (length bytes)) (%der-fail "truncated high-tag-number" pos))
            (let ((octet (aref bytes next)))
              (setf number (+ (ash number 7) (logand octet #x7f)))
              (incf next)
              (when (zerop (logand octet #x80)) (return)))
            (when (> number #x1fffffff) (%der-fail "tag number is too large" pos)))
          (when (< number 31) (%der-fail "non-minimal tag" pos))
          (values (logior (ash class 24) number) constructed next)))))

(defun %parse-one (bytes start limit)
  (multiple-value-bind (tag constructed after-tag) (%read-tag bytes start)
    (multiple-value-bind (length content-start) (%read-length bytes after-tag)
      (let ((end (+ content-start length)))
        (when (> end limit) (%der-fail "value extends past enclosing object" content-start))
        (when (and (member (logand tag #x1fffffff) '(16 17)) (not constructed))
          (%der-fail "constructed universal type encoded as primitive" start))
        (if constructed
            (let ((children '()) (pos content-start))
              (loop while (< pos end) do
                (multiple-value-bind (child next) (%parse-one bytes pos end)
                  (push child children) (setf pos next)))
              (values (%make-der-node tag t nil (nreverse children)) end))
            (let ((value (subseq bytes content-start end)))
              (when (and (= (logand tag #x1fffffff) 2)
                         (> (length value) 1)
                         (= (aref value 0) (if (logbitp 7 (aref value 1)) #xff 0)) )
                (%der-fail "non-minimal INTEGER" content-start))
              (when (and (= (logand tag #x1fffffff) 3)
                         (or (zerop (length value)) (> (aref value 0) 7)) )
                (%der-fail "invalid BIT STRING" content-start))
              (when (and (= (logand tag #x1fffffff) 3) (> (length value) 1)
                         (> (aref value 0) 0)
                         (not (zerop (logand (aref value (1- (length value)))
                                             (1- (ash 1 (aref value 0)))))))
                (%der-fail "non-zero unused BIT STRING bits" end))
              (when (and (= (logand tag #x1fffffff) 5) (plusp (length value)))
                (%der-fail "NULL must have zero length" content-start))
              (values (%make-der-node tag nil value nil) end)))))))

(defun der-decode (octets)
  (let ((bytes (%octets octets)))
    (multiple-value-bind (node end) (%parse-one bytes 0 (length bytes))
      (unless (= end (length bytes)) (%der-fail "trailing octets after DER object" end))
      node)))

(defun decode-der (octets) (der-decode octets))

(defun make-der-integer (integer)
  (check-type integer integer)
  (let ((bytes (if (>= integer 0)
                   (let ((out '()) (n integer))
                     (if (zerop n) '(0)
                         (progn (loop while (> n 0) do (push (logand n #xff) out) (setf n (ash n -8)))
                                (when (logbitp 7 (car out)) (push 0 out)) out)))
                   (let ((n integer) (out '()))
                     (loop do (push (logand n #xff) out) (setf n (ash n -8)) while (or (/= n -1) (not (logbitp 7 (car out))))) out))))
    (%make-der-node 2 nil (coerce bytes '(vector (unsigned-byte 8))) nil)))

(defun make-der-octet-string (octets) (%make-der-node 4 nil (%octets octets) nil))
(defun make-der-bit-string (octets &key (unused-bits 0))
  (check-type unused-bits (integer 0 7))
  (%make-der-node 3 nil (concatenate '(vector (unsigned-byte 8)) (vector unused-bits) (%octets octets)) nil))
(defun make-der-null () (%make-der-node 5 nil (make-array 0 :element-type '(unsigned-byte 8)) nil))
(defun make-der-oid (arcs)
  (when (or (< (length arcs) 2)
            (not (member (first arcs) '(0 1 2)))
            (some (lambda (arc) (or (not (integerp arc)) (< arc 0))) arcs)
            (and (< (first arcs) 2) (>= (second arcs) 40)))
    (error "Invalid OID arcs."))
  (let ((first (+ (* (first arcs) 40) (second arcs))) (out '()))
    (dolist (arc (cons first (cddr arcs)))
      (let ((parts (list (logand arc #x7f))) (n (ash arc -7)))
        (loop while (> n 0)
              do (push (logand n #x7f) parts)
                 (setf n (ash n -7)))
        (let ((digits parts))
          (setf out (nconc out
                           (loop for tail on digits
                                 for byte = (car tail)
                                 collect (if (cdr tail) (logior byte #x80) byte)))))))
    (%make-der-node 6 nil (coerce out '(vector (unsigned-byte 8))) nil)))
(defun make-der-sequence (&rest nodes) (%make-der-node 16 t nil nodes))
(defun make-der-set (&rest nodes) (%make-der-node 17 t nil nodes))

(defun der-integer-value (node)
  (check-type node der-node)
  (let ((bytes (%octets (der-node-value node))))
    (when (or (null bytes) (/= (der-node-tag node) 2)) (error "Not an INTEGER node."))
    (let ((n 0)) (map nil (lambda (byte) (setf n (+ (ash n 8) byte))) bytes)
      (if (logbitp 7 (aref bytes 0)) (- n (ash 1 (* 8 (length bytes)))) n))))

(defun der-oid-value (node)
  (let ((bytes (%octets (der-node-value node))) (arcs '()) (n 0))
    (check-type node der-node)
    (loop for byte across bytes do
      (setf n (+ (ash n 7) (logand byte #x7f)))
      (unless (logbitp 7 byte)
        (push n arcs)
        (setf n 0)))
    (when (and (plusp (length bytes)) (logbitp 7 (aref bytes (1- (length bytes)))))
      (%der-fail "truncated OID" nil))
    (setf arcs (nreverse arcs))
    (unless arcs (%der-fail "empty OID" nil))
    (let ((first (first arcs)))
      (cons (if (< first 40) 0 (if (< first 80) 1 2))
            (cons (if (< first 40) first (if (< first 80) (- first 40) (- first 80)))
                  (rest arcs))))))
