(in-package #:cl-tls-kit)

;;; TLS 1.3 handshake wire codec.  This file deliberately does not depend on
;;; the crypto layer: hashes, signatures, and certificate validation belong to
;;; callers.  All parsers consume exactly one bounded vector and reject
;;; truncation, trailing bytes, duplicate extensions, and non-canonical
;;; vector lengths.

(define-condition tls13-error (error)
  ((message :initarg :message :reader tls13-error-message))
  (:report (lambda (condition stream)
             (format stream "TLS 1.3 error: ~A" (tls13-error-message condition)))))
(define-condition tls13-decode-error (tls13-error) ())
(define-condition tls13-state-error (tls13-error) ())

(defun %tls13-fail (message &optional (condition 'tls13-decode-error))
  (error condition :message message))

(defun %tls13-octets (value)
  (unless (and (vectorp value) (every (lambda (x) (typep x '(unsigned-byte 8))) value))
    (%tls13-fail "expected an (unsigned-byte 8) vector"))
  value)

(defun %hs-u8 (n)
  (unless (typep n '(integer 0 255)) (%tls13-fail "octet out of range"))
  (vector n))
(defun %hs-u16 (n)
  (unless (typep n '(integer 0 65535)) (%tls13-fail "uint16 out of range"))
  (vector (ldb (byte 8 8) n) (ldb (byte 8 0) n)))
(defun %u24 (n)
  (unless (typep n '(integer 0 16777215)) (%tls13-fail "uint24 out of range"))
  (vector (ldb (byte 8 16) n) (ldb (byte 8 8) n) (ldb (byte 8 0) n)))
(defun %u32 (n)
  (unless (typep n '(integer 0 4294967295)) (%tls13-fail "uint32 out of range"))
  (vector (ldb (byte 8 24) n) (ldb (byte 8 16) n)
          (ldb (byte 8 8) n) (ldb (byte 8 0) n)))
(defun %cat (&rest vectors)
  (apply #'concatenate '(vector (unsigned-byte 8)) vectors))
(defun %read-integer (bytes pos width)
  (when (> (+ pos width) (length bytes)) (%tls13-fail "truncated integer"))
  (let ((n 0))
    (dotimes (i width (values n (+ pos width)))
      (setf n (+ (ash n 8) (aref bytes (+ pos i)))))))
(defun %bounded (bytes pos length)
  (when (or (< length 0) (> (+ pos length) (length bytes)))
    (%tls13-fail "truncated vector"))
  (values (subseq bytes pos (+ pos length)) (+ pos length)))
(defun %read-vector (bytes pos width &key (minimum 0) (maximum nil))
  (multiple-value-bind (length next) (%read-integer bytes pos width)
    (when (< length minimum) (%tls13-fail "vector shorter than its minimum"))
    (when (and maximum (> length maximum)) (%tls13-fail "vector exceeds its maximum"))
    (%bounded bytes next length)))
(defun %encode-vector (bytes width &key (minimum 0) (maximum nil))
  (%tls13-octets bytes)
  (let ((length (length bytes)))
    (when (< length minimum) (%tls13-fail "vector shorter than its minimum"))
    (when (and maximum (> length maximum)) (%tls13-fail "vector exceeds its maximum"))
    (%cat (ecase width (1 (%hs-u8 length)) (2 (%hs-u16 length)) (3 (%u24 length))) bytes)))
(defun %finish (bytes pos)
  (unless (= pos (length bytes)) (%tls13-fail "trailing bytes"))
  bytes)

(defstruct (tls-extension (:constructor make-tls-extension (type data)))
  (type 0) (data #()))
(defun %extension (type data)
  (unless (typep type '(integer 0 65535)) (%tls13-fail "extension type out of range"))
  (make-tls-extension type (%tls13-octets data)))
(defun %encode-extensions (extensions)
  (let ((seen '()) (body '()) (last-type nil))
    (dolist (extension extensions)
      (unless (typep extension 'tls-extension) (%tls13-fail "invalid extension"))
      (let ((type (tls-extension-type extension)))
        (when (member type seen) (%tls13-fail "duplicate extension"))
        (push type seen)
        (when (and last-type (= last-type 41)) (%tls13-fail "pre_shared_key must be last"))
        (setf last-type type)
        (push (%cat (%hs-u16 type) (%encode-vector (tls-extension-data extension) 2)) body)))
    (%encode-vector (apply #'%cat (nreverse body)) 2)))
(defun %decode-extensions (bytes pos)
  (multiple-value-bind (raw next) (%read-vector bytes pos 2)
    (let ((cursor 0) (out '()) (seen '()))
      (loop while (< cursor (length raw)) do
        (multiple-value-bind (type after-type) (%read-integer raw cursor 2)
          (multiple-value-bind (data after-data) (%read-vector raw after-type 2)
            (when (member type seen) (%tls13-fail "duplicate extension"))
            (push type seen)
            (push (make-tls-extension type data) out)
            (setf cursor after-data))))
      (when (and (member 41 seen) (/= 41 (tls-extension-type (car out))))
        (%tls13-fail "pre_shared_key must be the last extension"))
      (values (nreverse out) next))))

(defstruct (tls13-client-hello (:constructor make-tls13-client-hello
                                  (legacy-version random session-id cipher-suites extensions)))
  legacy-version random session-id cipher-suites extensions)
(defstruct (tls13-server-hello (:constructor make-tls13-server-hello
                                  (legacy-version random session-id cipher-suite extensions)))
  legacy-version random session-id cipher-suite extensions)
(defstruct (tls13-hello-retry-request (:constructor make-tls13-hello-retry-request
                                         (legacy-version selected-group extensions)))
  legacy-version selected-group extensions)
(defstruct (tls13-encrypted-extensions (:constructor make-tls13-encrypted-extensions (extensions))) extensions)
(defstruct (tls13-certificate-entry (:constructor make-tls13-certificate-entry (certificate extensions)))
  certificate extensions)
(defstruct (tls13-certificate (:constructor make-tls13-certificate (request-context entries)))
  request-context entries)
(defstruct (tls13-certificate-verify (:constructor make-tls13-certificate-verify (algorithm signature)))
  algorithm signature)
(defstruct (tls13-finished (:constructor make-tls13-finished (verify-data))) verify-data)
(defstruct (tls13-new-session-ticket (:constructor make-tls13-new-session-ticket
                                         (lifetime-age ticket-nonce ticket extensions
                                          &optional (ticket-age-add 0))))
  lifetime-age ticket-age-add ticket-nonce ticket extensions)
(defstruct (tls13-key-update (:constructor make-tls13-key-update (request))) request)
(defstruct (tls13-certificate-request (:constructor make-tls13-certificate-request
                                         (request-context extensions)))
  request-context extensions)

(defparameter *tls13-hrr-random*
  #(#xcf #x21 #xad #x74 #xe5 #x9a #x61 #x11 #xbe #x1d #x8c #x02 #x1e #x65 #xb8 #x91
    #xc2 #xa2 #x11 #x16 #x7a #xbb #x8c #x5e #x07 #x9e #x09 #xe2 #xc8 #xa8 #x33 #x9c))

(defun %valid-random (random)
  (unless (= (length (%tls13-octets random)) 32) (%tls13-fail "random must be 32 octets"))
  random)
(defun %valid-session-id (id) (%tls13-octets id) (when (> (length id) 32) (%tls13-fail "session id too long")) id)
(defun %cipher-suites (suites)
  (unless (and (vectorp suites) (evenp (length suites))) (%tls13-fail "cipher suite vector is malformed"))
  (every (lambda (x) (typep x '(integer 0 65535))) suites) suites)
(defun %encode-cipher-suites (suites)
  (%encode-vector (apply #'%cat (map 'list #'%hs-u16 suites)) 2 :minimum 2))
(defun %decode-cipher-suites (bytes pos)
  (multiple-value-bind (raw next) (%read-vector bytes pos 2 :minimum 2)
    (when (oddp (length raw)) (%tls13-fail "cipher suites length is not even"))
    (let ((out (make-array (/ (length raw) 2))) (cursor 0))
      (dotimes (i (length out) (values out next))
        (setf (aref out i) (nth-value 0 (%read-integer raw cursor 2)))
        (incf cursor 2)))))

(defun encode-client-hello (hello)
  (let* ((body (%cat (%hs-u16 (tls13-client-hello-legacy-version hello))
                     (%valid-random (tls13-client-hello-random hello))
                     (%encode-vector (%valid-session-id (tls13-client-hello-session-id hello)) 1)
                     (%encode-cipher-suites (%cipher-suites (tls13-client-hello-cipher-suites hello)))
                    (%encode-vector #(0) 1)))
         (extensions (%encode-extensions (tls13-client-hello-extensions hello))))
    (%cat body extensions)))
(defun decode-client-hello (bytes)
  (let ((bytes (%tls13-octets bytes)))
    (multiple-value-bind (version p1) (%read-integer bytes 0 2)
      (multiple-value-bind (random p2) (%bounded bytes p1 32)
        (multiple-value-bind (sid p3) (%read-vector bytes p2 1 :maximum 32)
          (multiple-value-bind (suites p4) (%decode-cipher-suites bytes p3)
            (multiple-value-bind (compression p5) (%read-vector bytes p4 1)
              (unless (equalp compression #(0)) (%tls13-fail "TLS 1.3 requires null compression"))
              (multiple-value-bind (extensions p6) (%decode-extensions bytes p5)
                (%finish bytes p6)
                (make-tls13-client-hello version random sid suites extensions)))))))))

(defun encode-server-hello (hello)
  (%cat (%hs-u16 (tls13-server-hello-legacy-version hello))
        (%valid-random (tls13-server-hello-random hello))
        (%encode-vector (%valid-session-id (tls13-server-hello-session-id hello)) 1)
        (%hs-u16 (tls13-server-hello-cipher-suite hello))
        #(0)
        (%encode-extensions (tls13-server-hello-extensions hello))))
(defun decode-server-hello (bytes)
  (setf bytes (%tls13-octets bytes))
  (let* ((version (nth-value 0 (%read-integer bytes 0 2)))
         (random-result (multiple-value-list (%bounded bytes 2 32)))
         (random (first random-result))
         (p2 (second random-result))
         (sid-result (multiple-value-list (%read-vector bytes p2 1 :maximum 32)))
         (sid (first sid-result))
         (p3 (second sid-result))
         (suite-result (multiple-value-list (%read-integer bytes p3 2)))
         (suite (first suite-result))
         (p4 (second suite-result)))
    (when (>= p4 (length bytes)) (%tls13-fail "truncated ServerHello"))
    (unless (= (aref bytes p4) 0) (%tls13-fail "ServerHello compression is not null"))
    (multiple-value-bind (extensions p5) (%decode-extensions bytes (1+ p4))
      (%finish bytes p5)
      (let ((ks (find 51 extensions :key #'tls-extension-type)))
        (if (equalp random *tls13-hrr-random*)
            (progn
              (unless (and ks (= (length (tls-extension-data ks)) 2))
                (%tls13-fail "HRR must contain a key_share extension"))
              (make-tls13-hello-retry-request
               version (nth-value 0 (%read-integer (tls-extension-data ks) 0 2)) extensions))
            (make-tls13-server-hello version random sid suite extensions))))))
(defun encode-hello-retry-request (hrr)
  (encode-server-hello
   (make-tls13-server-hello (tls13-hello-retry-request-legacy-version hrr)
                            *tls13-hrr-random* #() 0
                            (cons (make-tls-extension 51 (%hs-u16 (tls13-hello-retry-request-selected-group hrr)))
                                  (tls13-hello-retry-request-extensions hrr)))))

(defun encode-encrypted-extensions (message) (%encode-extensions (tls13-encrypted-extensions-extensions message)))
(defun decode-encrypted-extensions (bytes)
  (multiple-value-bind (extensions end) (%decode-extensions (%tls13-octets bytes) 0)
    (%finish bytes end) (make-tls13-encrypted-extensions extensions)))
(defun encode-certificate (message)
  (let* ((entries (mapcar
                   (lambda (entry)
                     (%cat
                      (%encode-vector (tls13-certificate-entry-certificate entry) 3)
                      (%encode-extensions (tls13-certificate-entry-extensions entry))))
                   (tls13-certificate-entries message)))
         (body (apply #'%cat entries)))
    (%cat (%encode-vector (tls13-certificate-request-context message) 1)
          (%encode-vector body 3))))
(defun decode-certificate (bytes)
  (setf bytes (%tls13-octets bytes))
  (multiple-value-bind (context p1) (%read-vector bytes 0 1)
    (multiple-value-bind (raw p2) (%read-vector bytes p1 3)
      (let ((cursor 0) (entries '()))
        (loop while (< cursor (length raw)) do
          (multiple-value-bind (certificate p3) (%read-vector raw cursor 3)
            (multiple-value-bind (extensions p4) (%decode-extensions raw p3)
              (push (make-tls13-certificate-entry certificate extensions) entries)
              (setf cursor p4))))
        (when (null entries) (%tls13-fail "Certificate must contain an entry"))
        (%finish bytes p2)
        (make-tls13-certificate context (nreverse entries))))))
(defun encode-certificate-verify (message)
  (%cat (%hs-u16 (tls13-certificate-verify-algorithm message))
        (%encode-vector (tls13-certificate-verify-signature message) 2)))
(defun decode-certificate-verify (bytes)
  (multiple-value-bind (algorithm p1) (%read-integer (%tls13-octets bytes) 0 2)
    (multiple-value-bind (signature p2) (%read-vector bytes p1 2 :minimum 1)
      (%finish bytes p2) (make-tls13-certificate-verify algorithm signature))))
(defun encode-finished (message) (%tls13-octets (tls13-finished-verify-data message)))
(defun decode-finished (bytes)
  (let ((bytes (%tls13-octets bytes)))
    (when (zerop (length bytes)) (%tls13-fail "Finished verify_data cannot be empty"))
    (make-tls13-finished bytes)))
(defun encode-new-session-ticket (message)
  (%cat (%u32 (tls13-new-session-ticket-lifetime-age message))
        (%u32 (tls13-new-session-ticket-ticket-age-add message))
        (%encode-vector (tls13-new-session-ticket-ticket-nonce message) 1)
        (%encode-vector (tls13-new-session-ticket-ticket message) 2 :minimum 1)
        (%encode-extensions (tls13-new-session-ticket-extensions message))))
(defun decode-new-session-ticket (bytes)
  (setf bytes (%tls13-octets bytes))
  (multiple-value-bind (age p1) (%read-integer bytes 0 4)
    (multiple-value-bind (unused p2) (%read-integer bytes p1 4)
      (multiple-value-bind (nonce p3) (%read-vector bytes p2 1)
        (multiple-value-bind (ticket p4) (%read-vector bytes p3 2 :minimum 1)
          (multiple-value-bind (extensions p5) (%decode-extensions bytes p4)
            (%finish bytes p5)
            (make-tls13-new-session-ticket age nonce ticket extensions unused)))))))
(defun encode-key-update (message)
  (let ((request (tls13-key-update-request message)))
    (unless (member request '(0 1)) (%tls13-fail "invalid KeyUpdate request"))
    (%hs-u8 request)))
(defun decode-key-update (bytes)
  (let ((bytes (%tls13-octets bytes)))
    (unless (= (length bytes) 1) (%tls13-fail "KeyUpdate has a one-octet body"))
    (unless (member (aref bytes 0) '(0 1)) (%tls13-fail "invalid KeyUpdate request"))
    (make-tls13-key-update (aref bytes 0))))
(defun encode-certificate-request (message)
  (%cat (%encode-vector (tls13-certificate-request-request-context message) 1)
        (%encode-extensions (tls13-certificate-request-extensions message))))
(defun decode-certificate-request (bytes)
  (setf bytes (%tls13-octets bytes))
  (multiple-value-bind (context p1) (%read-vector bytes 0 1)
    (multiple-value-bind (extensions p2) (%decode-extensions bytes p1)
      (%finish bytes p2) (make-tls13-certificate-request context extensions))))

(defparameter *tls13-message-codecs*
  '((1 . encode-client-hello) (2 . encode-server-hello) (8 . encode-encrypted-extensions)
    (11 . encode-certificate) (13 . encode-certificate-request) (15 . encode-certificate-verify)
    (20 . encode-finished) (4 . encode-new-session-ticket) (24 . encode-key-update)))
(defun encode-handshake (type message)
  (let ((encoder (cdr (assoc type *tls13-message-codecs*))))
    (unless encoder (%tls13-fail "unsupported handshake type"))
    (let ((body (funcall encoder message)))
      (%cat (%hs-u8 type) (%u24 (length body)) body))))
(defun decode-handshake (bytes)
  (setf bytes (%tls13-octets bytes))
  (when (< (length bytes) 4) (%tls13-fail "truncated handshake header"))
  (let ((type (aref bytes 0)) (length (nth-value 0 (%read-integer bytes 1 3))))
    (when (/= (+ 4 length) (length bytes)) (%tls13-fail "handshake length does not match input"))
    (let ((body (subseq bytes 4)))
      (case type
        (1 (decode-client-hello body)) (2 (decode-server-hello body)) (8 (decode-encrypted-extensions body))
        (11 (decode-certificate body)) (13 (decode-certificate-request body))
        (15 (decode-certificate-verify body)) (20 (decode-finished body))
        (4 (decode-new-session-ticket body)) (24 (decode-key-update body))
        (otherwise (%tls13-fail "unsupported handshake type"))))))

(defun tls13-certificate-verify-context (role)
  (cond ((eq role :client) "TLS 1.3, client CertificateVerify")
        ((eq role :server) "TLS 1.3, server CertificateVerify")
        (t (%tls13-fail "role must be :client or :server" 'tls13-state-error))))
(defun %ascii-octets (string)
  (coerce (map 'list #'char-code string) '(vector (unsigned-byte 8))))
(defun tls13-certificate-verify-input (role transcript)
  (%cat (make-array 64 :initial-element #x20 :element-type '(unsigned-byte 8))
        (%ascii-octets (tls13-certificate-verify-context role))
        #(0)
        (%tls13-octets transcript)))

(defstruct (tls13-state (:constructor make-tls13-state (role &optional (phase :start)))) role phase)
(defun %allowed-next-p (role phase type)
  (declare (ignore role))
  (case phase
    (:start (member type '(1 2)))
    (:client-hello (member type '(2 8)))
    (:server-hello (member type '(8 11 13 20)))
    (:encrypted-extensions (member type '(11 13 20)))
    (:certificate (member type '(15 20)))
    (:certificate-verify (eql type 20))
    (:connected (member type '(4 24)))
    (otherwise nil)))
(defun tls13-state-advance (state type)
  (unless (%allowed-next-p (tls13-state-role state) (tls13-state-phase state) type)
    (%tls13-fail "handshake message is not valid in this state" 'tls13-state-error))
  (setf (tls13-state-phase state)
        (case type (1 :client-hello) (2 :server-hello) (8 :encrypted-extensions)
          (11 :certificate) (13 :certificate) (15 :certificate-verify)
          (20 :connected) (4 :connected) (24 :connected)))
  state)
