(in-package #:cl-tls-kit)

(define-condition pem-error (error)
  ((message :initarg :message :reader pem-error-message))
  (:report (lambda (condition stream) (format stream "PEM error: ~A" (pem-error-message condition)))))

(defstruct (pem-block (:constructor %make-pem-block (label der)))
  label der)

(defun make-pem-block (&key label der)
  (unless (and (stringp label) (plusp (length label))
               (every (lambda (c) (or (alphanumericp c) (char= c #\-) (char= c #\space))) label))
    (error 'pem-error :message "invalid PEM label"))
  (%make-pem-block label der))

(defparameter *base64-alphabet* "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/")

(defun %base64-encode (octets)
  (with-output-to-string (out)
    (loop for i from 0 below (length octets) by 3
          for left = (- (length octets) i)
          for a = (aref octets i)
          for b = (if (> left 1) (aref octets (+ i 1)) 0)
          for c = (if (> left 2) (aref octets (+ i 2)) 0)
          do (write-char (char *base64-alphabet* (ash a -2)) out)
             (write-char (char *base64-alphabet* (logior (ash (logand a 3) 4) (ash b -4))) out)
             (write-char (if (> left 1) (char *base64-alphabet* (logior (ash (logand b 15) 2) (ash c -6))) #\=) out)
             (write-char (if (> left 2) (char *base64-alphabet* (logand c 63)) #\=) out))))

(defun %base64-value (character)
  (position character *base64-alphabet* :test #'char=))

(defun %base64-decode (text)
  (let ((clean (remove-if (lambda (c) (find c (list #\space #\tab #\return #\newline) :test #'char=)) text)))
    (when (or (zerop (length clean)) (/= (mod (length clean) 4) 0))
      (error 'pem-error :message "invalid base64 length"))
    (with-output-to-string (ignored)
      (declare (ignore ignored)))
    (let ((out (make-array 0 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0)))
      (loop for i from 0 below (length clean) by 4
            for a = (%base64-value (char clean i))
            for b = (%base64-value (char clean (+ i 1)))
            for cchar = (char clean (+ i 2))
            for dchar = (char clean (+ i 3))
            for c = (and (char/= cchar #\=) (%base64-value cchar))
            for d = (and (char/= dchar #\=) (%base64-value dchar))
            do (when (or (null a) (null b) (and (char/= cchar #\=) (null c))
                         (and (char/= dchar #\=) (null d)))
                 (error 'pem-error :message "invalid base64 character"))
               (when (and (or (char= cchar #\=) (char= dchar #\=)) (/= i (- (length clean) 4)))
                 (error 'pem-error :message "padding is not final"))
               (when (and (char= cchar #\=) (not (char= dchar #\=)))
                 (error 'pem-error :message "invalid base64 padding"))
               (vector-push-extend (logior (ash a 2) (ash b -4)) out)
               (when c (vector-push-extend (logior (ash (logand b 15) 4) (ash c -2)) out))
               (when d (vector-push-extend (logior (ash (logand c 3) 6) d) out)))
      (coerce out '(vector (unsigned-byte 8))))))

(defun pem-encode (blocks)
  (with-output-to-string (out)
    (dolist (block (if (listp blocks) blocks (list blocks)))
      (format out "-----BEGIN ~A-----~%" (pem-block-label block))
      (let ((base64 (%base64-encode (pem-block-der block))))
        (loop for start from 0 below (length base64) by 64
              do (write-line (subseq base64 start (min (+ start 64) (length base64))) out)))
      (format out "-----END ~A-----~%" (pem-block-label block)))))

(defun encode-pem (blocks) (pem-encode blocks))

(defun pem-decode (text)
  (unless (stringp text) (error 'type-error :datum text :expected-type 'string))
  (let ((position 0) (blocks '()))
    (loop
      (let ((begin (search "-----BEGIN " text :start2 position)))
        (unless begin (return))
        (let* ((label-start (+ begin 11)) (header-end (search "-----" text :start2 label-start)))
          (unless header-end (error 'pem-error :message "unterminated BEGIN line"))
          (let* ((label (subseq text label-start header-end))
                 (body-start (+ header-end 5))
                 (end-marker (format nil "-----END ~A-----" label))
                 (end (search end-marker text :start2 body-start)))
            (unless end (error 'pem-error :message "missing matching END line"))
            (push (%make-pem-block label (%base64-decode (subseq text body-start end))) blocks)
            (setf position (+ end (length end-marker)))))))
    (nreverse blocks)))

(defun decode-pem (text) (pem-decode text))
