(in-package #:cl-tls-kit.x509)

(define-condition x509-error (error)
  ((reason :initarg :reason :reader x509-error-reason))
  (:report (lambda (c s) (format s "Invalid X.509 certificate: ~A"
                                  (x509-error-reason c)))))

(defstruct der tag content raw)
(defstruct x509-public-key type algorithm parameters data)
(defstruct x509-certificate version serial-number issuer subject not-before not-after
  public-key signature-algorithm tbs-certificate signature extensions basic-constraints key-usage
  extended-key-usage subject-alternative-name name-constraints)

(defun %fail (format-control &rest args)
  (error 'x509-error :reason (apply #'format nil format-control args)))

(declaim (ftype function %pem-octets))

(defun %octets (object)
  (cond ((typep object '(vector (unsigned-byte 8))) object)
        ((stringp object)
         (let ((blocks (cl-tls-kit:pem-decode object)))
           (unless (= (length blocks) 1)
             (%fail "expected one PEM block"))
           (cl-tls-kit:pem-block-der (first blocks))))
        ((streamp object) (let ((s (make-array (file-length object)
                                               :element-type '(unsigned-byte 8))))
                            (read-sequence s object) (%octets s)))
        (t (%fail "expected DER octets or PEM string"))))

(defun %base64-value (c)
  (cond ((and (char>= c #\A) (char<= c #\Z)) (- (char-code c) (char-code #\A)))
        ((and (char>= c #\a) (char<= c #\z)) (+ 26 (- (char-code c) (char-code #\a))))
        ((and (char>= c #\0) (char<= c #\9)) (+ 52 (- (char-code c) (char-code #\0))))
        ((char= c #\+) 62) ((char= c #\/) 63) (t nil)))

(defun %pem-octets (s)
  (let ((start (or (search "-----BEGIN CERTIFICATE-----" s)
                   (%fail "PEM certificate header not found")))
        (end (search "-----END CERTIFICATE-----" s)))
    (unless end (%fail "PEM certificate footer not found"))
    (let ((chars (remove-if-not #'%base64-value
                                (subseq s (+ start 27) end)))
          (out (make-array 0 :element-type '(unsigned-byte 8)
                             :adjustable t :fill-pointer 0)))
      (loop for i from 0 below (length chars) by 4
            for a = (%base64-value (char chars i))
            for b = (and (< (1+ i) (length chars)) (%base64-value (char chars (1+ i))))
            for c = (and (< (+ i 2) (length chars)) (%base64-value (char chars (+ i 2))))
            for d = (and (< (+ i 3) (length chars)) (%base64-value (char chars (+ i 3))))
            do (vector-push-extend (logior (ash a 2) (ash b -4)) out)
               (when c (vector-push-extend (logior (ash (logand b 15) 4) (ash c -2)) out))
               (when d (vector-push-extend (logior (ash (logand c 3) 6) d) out))
            finally (return out)))))

(defun %read-der (bytes &optional (at 0))
  (when (>= at (length bytes)) (%fail "truncated DER tag"))
  (let* ((tag (aref bytes at)) (p (1+ at)) (first (aref bytes p)) (p (1+ p))
         (length (if (< first 128) first
                     (let ((n (logand first 127)) (v 0))
                       (when (or (zerop n) (> n 4) (> (+ p n) (length bytes)))
                         (%fail "invalid DER length"))
                       (dotimes (i n v) (setf v (+ (ash v 8) (aref bytes (+ p i)))))
                       (incf p n) v))))
    (when (> (+ p length) (length bytes)) (%fail "truncated DER value"))
    (values (make-der :tag tag :content (subseq bytes p (+ p length))
                      :raw (subseq bytes at (+ p length))) (+ p length))))

(defun %children (d)
  (let ((p 0) (c (der-content d)) (out nil))
    (loop while (< p (length c)) do
      (multiple-value-bind (x next) (%read-der c p) (push x out) (setf p next)))
    (nreverse out)))

(defun %integer (d)
  (let ((v 0))
    (loop for b across (der-content d) do (setf v (+ (ash v 8) b)))
    v))
(defun %oid (d)
  (let ((b (der-content d)) (parts nil) (v 0))
    (when (zerop (length b)) (%fail "empty OID"))
    (let ((first (aref b 0))) (push (floor first 40) parts) (push (mod first 40) parts))
    (loop for i from 1 below (length b) do
      (setf v (+ (ash v 7) (logand (aref b i) 127)))
      (when (zerop (logand (aref b i) 128)) (push v parts) (setf v 0)))
    (when (plusp v) (%fail "truncated OID"))
    (format nil "~{~A~^.~}" (nreverse parts))))
(defun %string (d)
  (map 'string #'code-char (der-content d)))

(defun %time (d)
  (let* ((s (%string d)) (generalized (= (der-tag d) #x18))
         (digits (if generalized s (concatenate 'string "20" s)))
         (n (lambda (a b) (parse-integer digits :start a :end b)))
         (year (funcall n 0 4)) (month (funcall n 4 6)) (day (funcall n 6 8))
         (hour (funcall n 8 10)) (minute (funcall n 10 12)) (second (funcall n 12 14)))
    (unless (char= (char s (1- (length s))) #\Z) (%fail "non-UTC certificate time"))
    (encode-universal-time second minute hour day month year 0)))

(defun %name (d)
  (mapcar (lambda (set)
            (mapcar (lambda (ava) (let ((a (%children ava)))
                                    (cons (%oid (first a)) (%string (second a)))))
                    (%children set)))
          (%children d)))

(defun x509-name-string (name)
  (with-output-to-string (out)
    (loop for rdn in name for first-rdn = t then nil do
      (unless first-rdn (write-char #\, out))
      (loop for ava in rdn for first-ava = t then nil do
        (unless first-ava (write-char #\+ out))
        (format out "~A=~A" (car ava) (cdr ava))))))

(defun %bit-set-p (bits n)
  (let ((content (der-content bits)))
    (and (> (length content) 1)
         (< n (- (* 8 (1- (length content))) (aref content 0)))
         (not (zerop (logand (aref content (1+ (floor n 8)))
                             (ash 1 (- 7 (mod n 8)))))))))

(defun %key-usage (bits)
  (loop for (name position) in '((:digital-signature 0) (:non-repudiation 1)
                                 (:key-encipherment 2) (:data-encipherment 3)
                                 (:key-agreement 4) (:key-cert-sign 5)
                                 (:crl-sign 6) (:encipher-only 7) (:decipher-only 8))
        when (%bit-set-p bits position) collect name))

(defun %basic-constraints (sequence)
  (let ((a (%children sequence)))
    (list :ca (and (first a) (= (der-tag (first a)) #x01)
                   (= (aref (der-content (first a)) 0) 255))
          :path-length (when (and (first a) (= (der-tag (first a)) #x01)
                                  (second a)) (%integer (second a))))))

(defun %general-names (sequence)
  (mapcar (lambda (name)
            (cons (case (der-tag name)
                    (#x81 :rfc822) (#x82 :dns) (#x86 :uri) (#x87 :ip)
                    (#xa4 :directory-name) (t :other))
                  (if (= (der-tag name) #x87)
                      (der-content name)
                      (if (member (der-tag name) '(#x81 #x82 #x86))
                          (%string name) name))))
          (%children sequence)))

(defun %algorithm (d)
  (let ((a (%children d))) (values (%oid (first a)) (and (second a) (der-content (second a))))))

(defun %spki (d)
  (let* ((a (%children d)) (alg (first a)) (bits (second a)))
    (multiple-value-bind (oid params) (%algorithm alg)
      (cond
        ((string= oid "1.2.840.113549.1.1.1")
         (let ((k (%children (first (%children
                                     (make-der :tag #x30 :content (subseq (der-content bits) 1)
                                               :raw nil))))))
           (make-x509-public-key :type :rsa :algorithm oid :parameters params
                                 :data (list :modulus (%integer (first k)) :exponent (%integer (second k))))))
        ((string= oid "1.2.840.10045.2.1")
         (let ((curve (and params (%oid (make-der :tag #x06 :content params :raw nil)))))
           (unless (member curve '("1.2.840.10045.3.1.7" "1.3.132.0.34") :test #'string=)
             (%fail "unsupported EC curve ~A" curve))
           (make-x509-public-key :type :ec :algorithm oid :parameters curve
                                 :data (der-content bits))))
        ((string= oid "1.3.101.112")
         (make-x509-public-key :type :ed25519 :algorithm oid :parameters params
                               :data (der-content bits)))
        (t (%fail "unsupported public-key algorithm ~A" oid))))))

(defun %extension (d)
  (let* ((a (%children d)) (oid (%oid (first a))) (critical (and (> (length a) 2) (= (der-tag (second a)) #x01)
                                                                    (= (aref (der-content (second a)) 0) 255)))
         (value (der-content (car (last a))))
         (known '("2.5.29.19" "2.5.29.15" "2.5.29.37" "2.5.29.17" "2.5.29.30")))
    (when (and critical (not (member oid known :test #'string=))) (%fail "unknown critical extension ~A" oid))
    (multiple-value-bind (parsed ignored) (%read-der value)
      (declare (ignore ignored))
      (values oid critical parsed))))

(defun %parse-extensions (wrapper)
  (let ((result nil))
    (dolist (ext (%children (first (%children wrapper))))
      (multiple-value-bind (oid critical value) (%extension ext)
        (push (cons oid (list :critical critical :value value)) result)))
    (nreverse result)))

(defun %find-ext (extensions oid)
  (cdr (assoc oid extensions :test #'string=)))

(defun %parse-certificate (bytes)
  (multiple-value-bind (outer end) (%read-der bytes)
    (unless (and (= (der-tag outer) #x30) (= end (length bytes))) (%fail "certificate is not one DER SEQUENCE"))
    (let* ((parts (%children outer)) (tbs (first parts)) (sigalg (second parts)) (tc (%children tbs))
           (i 0) (version 1))
      (when (= (logand (der-tag (nth i tc)) #xe0) #xa0)
        (setf version (1+ (%integer (first (%children (nth i tc))))) i (1+ i)))
      (let* ((serial (%integer (nth i tc))) (issuer (nth (+ i 2) tc))
             (validity (nth (+ i 3) tc)) (subject (nth (+ i 4) tc)) (spki (nth (+ i 5) tc))
             (extensions nil))
        (dolist (extra (nthcdr (+ i 6) tc)) (when (= (der-tag extra) #xa3) (setf extensions (%parse-extensions extra))))
        (let ((bc (%find-ext extensions "2.5.29.19")) (ku (%find-ext extensions "2.5.29.15"))
              (eku (%find-ext extensions "2.5.29.37")) (san (%find-ext extensions "2.5.29.17"))
              (nc (%find-ext extensions "2.5.29.30")) (v (%children validity)))
          (make-x509-certificate :version version :serial-number serial :issuer (%name issuer)
            :subject (%name subject) :not-before (%time (first v)) :not-after (%time (second v))
            :public-key (%spki spki) :signature-algorithm (multiple-value-bind (o) (%algorithm sigalg) o)
            :tbs-certificate (der-raw tbs)
            :signature (let ((value (der-content (third parts))))
                         (if (and (plusp (length value)) (zerop (aref value 0)))
                             (subseq value 1)
                             (%fail "certificate signature has unused bits")))
            :extensions extensions :basic-constraints (and bc (%basic-constraints (getf bc :value)))
            :key-usage (and ku (%key-usage (getf ku :value)))
            :extended-key-usage (and eku (mapcar #'%oid (%children (getf eku :value))))
            :subject-alternative-name (and san (%general-names (getf san :value)))
            :name-constraints (and nc (getf nc :value))))))))

(defun parse-certificate-der (der) (%parse-certificate (%octets der)))
(defun parse-x509-certificate (input) (parse-certificate-der input))
(defun parse-certificate (input) (parse-certificate-der input))

(defun x509-rsa-public-key-modulus (key) (getf (x509-public-key-data key) :modulus))
(defun x509-rsa-public-key-exponent (key) (getf (x509-public-key-data key) :exponent))
(defun x509-ec-public-key-curve (key) (x509-public-key-parameters key))
(defun x509-ec-public-key-point (key) (x509-public-key-data key))
(defun x509-ed25519-public-key-point (key) (x509-public-key-data key))
