(in-package #:cl-tls-kit.x509)

(define-condition x509-error (error)
  ((reason :initarg :reason :reader x509-error-reason))
  (:report (lambda (c s) (format s "Invalid X.509 certificate: ~A"
                                  (x509-error-reason c)))))

(defstruct der tag content raw)
(defstruct x509-public-key type algorithm parameters data)
(defstruct x509-certificate version serial-number issuer subject not-before not-after
  public-key signature-algorithm tbs-signature-algorithm tbs-certificate signature extensions basic-constraints key-usage
  extended-key-usage subject-alternative-name name-constraints)

(defparameter +x509-max-certificate-bytes+ (* 1024 1024))
(defparameter +x509-max-der-depth+ 32)
(defparameter *x509-der-depth* 0)

(defun %fail (format-control &rest args)
  (error 'x509-error :reason (apply #'format nil format-control args)))

(declaim (ftype function %pem-octets))

(defun %octets (object)
  (cond ((typep object '(vector (unsigned-byte 8))) object)
        ((stringp object)
         (when (> (length object) (* 2 +x509-max-certificate-bytes+))
           (%fail "PEM certificate input is too large"))
         (%pem-octets object))
        ((streamp object)
         (let ((size (file-length object)))
           (if size
               (progn
                 (unless (<= size +x509-max-certificate-bytes+)
                   (%fail "certificate input is too large"))
                 (let ((s (make-array size :element-type '(unsigned-byte 8))))
                   (unless (= (read-sequence s object) size)
                     (%fail "short certificate input"))
                   (%octets s)))
               (let ((out (make-array 0 :element-type '(unsigned-byte 8)
                                      :adjustable t :fill-pointer 0))
                     (buffer (make-array 4096 :element-type '(unsigned-byte 8))))
                 (loop for count = (read-sequence buffer object)
                       while (plusp count)
                       do (when (> (+ (length out) count) +x509-max-certificate-bytes+)
                            (%fail "certificate input is too large"))
                          (loop for i below count do (vector-push-extend (aref buffer i) out)))
                 (%octets (coerce out '(vector (unsigned-byte 8))))))))
        (t (%fail "expected DER octets or PEM string"))))

(defun %base64-value (c)
  (cond ((and (char>= c #\A) (char<= c #\Z)) (- (char-code c) (char-code #\A)))
        ((and (char>= c #\a) (char<= c #\z)) (+ 26 (- (char-code c) (char-code #\a))))
        ((and (char>= c #\0) (char<= c #\9)) (+ 52 (- (char-code c) (char-code #\0))))
        ((char= c #\+) 62) ((char= c #\/) 63) (t nil)))

(defun %pem-octets (s)
  (when (> (length s) (* 2 +x509-max-certificate-bytes+))
    (%fail "PEM certificate input is too large"))
  (let ((start (or (search "-----BEGIN CERTIFICATE-----" s)
                   (%fail "PEM certificate header not found")))
        (end (search "-----END CERTIFICATE-----" s)))
    (unless end (%fail "PEM certificate footer not found"))
    (let* ((body (subseq s (+ start 27) end))
           (chars (remove-if (lambda (c)
                               (member c '(#\space #\tab #\return #\newline)
                                       :test #'char=))
                             body))
          (out (make-array 0 :element-type '(unsigned-byte 8)
                             :adjustable t :fill-pointer 0)))
      (unless (and (zerop (mod (length chars) 4))
                   (every (lambda (c) (or (%base64-value c) (char= c #\=))) chars))
        (%fail "invalid PEM base64"))
      (unless (zerop (mod (length chars) 4))
        (%fail "invalid PEM base64 length"))
      (loop for i from 0 below (length chars) by 4
            for a = (%base64-value (char chars i))
            for b = (and (< (1+ i) (length chars)) (%base64-value (char chars (1+ i))))
            for c = (and (< (+ i 2) (length chars)) (%base64-value (char chars (+ i 2))))
            for d = (and (< (+ i 3) (length chars)) (%base64-value (char chars (+ i 3))))
            do (when (or (null a) (null b)
                         (and (< i (- (length chars) 4))
                              (or (char= (char chars (+ i 2)) #\=)
                                  (char= (char chars (+ i 3)) #\=)))
                         (and (char= (char chars (+ i 2)) #\=)
                              (not (char= (char chars (+ i 3)) #\=)))
                         (and (char= (char chars (+ i 2)) #\=)
                              (not (zerop (logand b 15))))
                         (and (char= (char chars (+ i 3)) #\=)
                              (not (zerop (logand c 3)))))
                 (%fail "invalid PEM base64 padding"))
               (vector-push-extend (logior (ash a 2) (ash b -4)) out)
               (when c (vector-push-extend (logior (ash (logand b 15) 4) (ash c -2)) out))
               (when d (vector-push-extend (logior (ash (logand c 3) 6) d) out))
            finally (return out)))))

(defun %read-der (bytes &optional (at 0))
  (unless (<= *x509-der-depth* +x509-max-der-depth+)
    (%fail "DER nesting depth exceeds limit"))
  (when (>= at (length bytes)) (%fail "truncated DER tag"))
  (let* ((tag (aref bytes at)) (p (1+ at)))
    (when (= (logand tag #x1f) #x1f)
      (%fail "high-tag-number DER is unsupported"))
    (when (>= p (length bytes)) (%fail "truncated DER length"))
    (let* ((first (aref bytes p)) (p (1+ p))
         (length (if (< first 128) first
                     (let ((n (logand first 127)) (v 0))
                       (when (or (zerop n) (> n 4) (> (+ p n) (length bytes)))
                         (%fail "invalid DER length"))
                       (when (zerop (aref bytes p))
                         (%fail "non-minimal DER length"))
                       (dotimes (i n v) (setf v (+ (ash v 8) (aref bytes (+ p i)))))
                       (when (< v 128) (%fail "non-minimal DER length"))
                       (incf p n) v))))
      (when (or (> length +x509-max-certificate-bytes+)
                (> (+ p length) (length bytes)))
        (%fail "truncated or oversized DER value"))
      (values (make-der :tag tag :content (subseq bytes p (+ p length))
                        :raw (subseq bytes at (+ p length))) (+ p length)))))

(defun %validate-oid-content (content)
  (when (zerop (length content)) (%fail "empty OID"))
  (let ((start 0))
    (loop for i from 0 below (length content)
          for octet = (aref content i)
          do (when (and (= i start) (logbitp 7 octet)
                        (zerop (logand octet #x7f)))
               (%fail "non-minimal OID subidentifier"))
             (when (zerop (logand octet #x80))
               (setf start (1+ i)))
          finally (when (/= start (length content)) (%fail "truncated OID")))))

(defun %validate-der-node (d)
  (let* ((tag (der-tag d))
         (class (logand tag #xc0))
         (number (logand tag #x1f))
         (constructed (not (zerop (logand tag #x20))))
         (content (der-content d)))
    (when (and (zerop class) (if (member number '(16 17))
                                 (not constructed)
                                 constructed))
      (%fail "invalid constructed bit for universal DER type"))
    (when (and (zerop class) (= number 1))
      (unless (and (= (length content) 1)
                   (member (aref content 0) '(0 255)))
        (%fail "invalid DER BOOLEAN")))
    (when (and (zerop class) (= number 3))
      (unless (and (plusp (length content)) (<= (aref content 0) 7))
        (%fail "invalid DER BIT STRING"))
      (when (and (> (aref content 0) 0)
                 (or (= (length content) 1)
                     (not (zerop (logand (aref content (1- (length content)))
                                         (1- (ash 1 (aref content 0))))))))
        (%fail "non-zero unused DER BIT STRING bits")))
    (when (and (zerop class) (= number 6))
      (%validate-oid-content content))
    d))

(defun %der-octets< (left right)
  (loop for i from 0 below (min (length left) (length right))
        for a = (aref left i)
        for b = (aref right i)
        when (/= a b) do (return (< a b))
        finally (return (< (length left) (length right)))))

(defun %validate-der-tree (d &optional (depth 0))
  (when (> depth +x509-max-der-depth+)
    (%fail "DER nesting depth exceeds limit"))
  (%validate-der-node d)
  (when (not (zerop (logand (der-tag d) #x20)))
    (let ((p 0) (c (der-content d)) (previous nil))
      (loop while (< p (length c)) do
        (multiple-value-bind (child next) (%read-der c p)
          (%validate-der-tree child (1+ depth))
          (when (and (= (der-tag d) #x31) previous
                     (%der-octets< (der-raw child) (der-raw previous)))
            (%fail "DER SET members are not sorted"))
          (setf previous child)
          (setf p next)))))
  d)

(defun %children (d)
  (%validate-der-tree d)
  (let ((*x509-der-depth* (1+ *x509-der-depth*))
        (p 0) (c (der-content d)) (out nil))
    (when (> *x509-der-depth* +x509-max-der-depth+)
      (%fail "DER nesting depth exceeds limit"))
    (loop while (< p (length c)) do
      (multiple-value-bind (x next) (%read-der c p) (push x out) (setf p next)))
    (nreverse out)))

(defun %integer (d)
  (let ((bytes (der-content d)) (v 0))
    (when (or (zerop (length bytes))
              (and (> (length bytes) 1)
                   (zerop (aref bytes 0))
                   (< (aref bytes 1) 128))
              (plusp (logand (aref bytes 0) 128)))
      (%fail "non-canonical or negative DER INTEGER"))
    (loop for b across bytes do (setf v (+ (ash v 8) b)))
    v))
(defun %oid (d)
  (let ((b (der-content d)) (subidentifiers nil) (v 0))
    (%validate-oid-content b)
    (loop for octet across b do
      (setf v (+ (ash v 7) (logand octet #x7f)))
      (when (zerop (logand octet #x80))
        (push v subidentifiers)
        (setf v 0)))
    (let* ((values (nreverse subidentifiers))
           (first (first values))
           (rest (rest values))
           (first-arc (if (< first 40) 0 (if (< first 80) 1 2)))
           (second-arc (if (< first 40) first (if (< first 80) (- first 40) (- first 80)))))
      (format nil "~{~A~^.~}" (cons first-arc (cons second-arc rest))))))
(defun %string (d)
  (map 'string #'code-char (der-content d)))

(defun %time (d)
  (let* ((s (%string d)) (generalized (= (der-tag d) #x18))
         (length (if generalized 15 13)))
    (unless (and (= (length s) length) (char= (char s (1- length)) #\Z)
                 (every #'digit-char-p (subseq s 0 (1- length))))
      (%fail "invalid UTC certificate time"))
    (let* ((year-digits (if generalized 4 2))
           (raw-year (parse-integer s :end year-digits))
           (year (if generalized raw-year
                     (+ (if (< raw-year 50) 2000 1900) raw-year)))
           (n (lambda (a b) (parse-integer s :start a :end b)))
           (month (funcall n year-digits (+ year-digits 2)))
           (day (funcall n (+ year-digits 2) (+ year-digits 4)))
           (hour (funcall n (+ year-digits 4) (+ year-digits 6)))
           (minute (funcall n (+ year-digits 6) (+ year-digits 8)))
           (second (funcall n (+ year-digits 8) (+ year-digits 10))))
      (encode-universal-time second minute hour day month year 0))))

(defun %name (d)
  (mapcar (lambda (set)
            (mapcar (lambda (ava) (let ((a (%children ava)))
                                    (cons (%oid (first a)) (%string (second a)))))
                    (%children set)))
          (%children d)))

(defun x509-name-string (name)
  (with-output-to-string (out)
    (loop for rdn in name for first-rdn = t then nil do
      (unless first-rdn (write-char #\, out))
      (loop for ava in rdn for first-ava = t then nil do
        (unless first-ava (write-char #\+ out))
        (format out "~A=~A" (car ava) (cdr ava))))))

(defun %bit-set-p (bits n)
  (let ((content (der-content bits)))
    (and (> (length content) 1)
         (< n (- (* 8 (1- (length content))) (aref content 0)))
         (not (zerop (logand (aref content (1+ (floor n 8)))
                             (ash 1 (- 7 (mod n 8)))))))))

(defun %key-usage (bits)
  (loop for (name position) in '((:digital-signature 0) (:non-repudiation 1)
                                 (:key-encipherment 2) (:data-encipherment 3)
                                 (:key-agreement 4) (:key-cert-sign 5)
                                 (:crl-sign 6) (:encipher-only 7) (:decipher-only 8))
        when (%bit-set-p bits position) collect name))

(defun %basic-constraints (sequence)
  (let ((a (%children sequence)))
    (list :ca (and (first a) (= (der-tag (first a)) #x01)
                   (= (length (der-content (first a))) 1)
                   (= (aref (der-content (first a)) 0) 255))
          :path-length (when (and (first a) (= (der-tag (first a)) #x01)
                                  (second a)) (%integer (second a))))))

(defun %general-names (sequence)
  (mapcar (lambda (name)
            (list (case (der-tag name)
                    (#x81 :rfc822) (#x82 :dns) (#x86 :uri) (#x87 :ip)
                    (#xa4 :directory-name) (t :other))
                  (if (= (der-tag name) #x87)
                      (der-content name)
                      (if (member (der-tag name) '(#x81 #x82 #x86))
                          (%string name) name))))
          (%children sequence)))

(defun %algorithm (d)
  (let ((a (%children d))) (values (%oid (first a)) (and (second a) (der-content (second a))))))

(defun %spki (d)
  (let* ((a (%children d)) (alg (first a)) (bits (second a)))
    (multiple-value-bind (oid params) (%algorithm alg)
      (cond
        ((string= oid "1.2.840.113549.1.1.1")
         (let ((k (%children (first (%children
                                     (make-der :tag #x30 :content (subseq (der-content bits) 1)
                                               :raw nil))))))
           (make-x509-public-key :type :rsa :algorithm oid :parameters params
                                 :data (list :modulus (%integer (first k)) :exponent (%integer (second k))))))
        ((string= oid "1.2.840.10045.2.1")
         (let ((curve (and params (%oid (make-der :tag #x06 :content params :raw nil)))))
           (unless (member curve '("1.2.840.10045.3.1.7" "1.3.132.0.34") :test #'string=)
             (%fail "unsupported EC curve ~A" curve))
         (make-x509-public-key :type :ec :algorithm oid :parameters curve
                                 :data (subseq (der-content bits) 1))))
        ((string= oid "1.3.101.112")
         (make-x509-public-key :type :ed25519 :algorithm oid :parameters params
                               :data (subseq (der-content bits) 1)))
        (t (%fail "unsupported public-key algorithm ~A" oid))))))

(defun %extension (d)
  (let* ((a (%children d)) (oid (%oid (first a))) (critical (and (> (length a) 2) (= (der-tag (second a)) #x01)
                                                                    (= (aref (der-content (second a)) 0) 255)))
         (value (der-content (car (last a))))
         (known '("2.5.29.19" "2.5.29.15" "2.5.29.37" "2.5.29.17" "2.5.29.30")))
    (when (and critical (not (member oid known :test #'string=))) (%fail "unknown critical extension ~A" oid))
    (multiple-value-bind (parsed end) (%read-der value)
      (unless (= end (length value)) (%fail "extension value has trailing DER"))
      (values oid critical parsed))))

(defun %parse-extensions (wrapper)
  (let ((result nil))
    (dolist (ext (%children (first (%children wrapper))))
      (multiple-value-bind (oid critical value) (%extension ext)
        (push (cons oid (list :critical critical :value value)) result)))
    (nreverse result)))

(defun %general-subtrees (sequence)
  (mapcar (lambda (subtree)
            (let ((base (first (%children subtree))))
              (case (der-tag base)
                (#x82 (list :dns (%string base)))
                (#x87 (list :ip (der-content base)))
                (t (list :unsupported base)))))
          (%children sequence)))

(defun %name-constraints (sequence critical)
  (let ((permitted nil) (excluded nil))
    (dolist (field (%children sequence))
      (case (der-tag field)
        (#xa0 (setf permitted (%general-subtrees (make-der :tag #x30
                                                           :content (der-content field)
                                                           :raw nil))))
        (#xa1 (setf excluded (%general-subtrees (make-der :tag #x30
                                                          :content (der-content field)
                                                          :raw nil))))))
    (list :critical critical :permitted-subtrees permitted :excluded-subtrees excluded)))

(defun %find-ext (extensions oid)
  (cdr (assoc oid extensions :test #'string=)))

(defun %parse-certificate (bytes)
  (when (> (length bytes) +x509-max-certificate-bytes+)
    (%fail "certificate input is too large"))
  (multiple-value-bind (outer end) (%read-der bytes)
    (unless (and (= (der-tag outer) #x30) (= end (length bytes))) (%fail "certificate is not one DER SEQUENCE"))
    (let* ((parts (%children outer)) (tbs (first parts)) (sigalg (second parts)) (tc (%children tbs))
           (i 0) (version 1))
      (unless (and (= (length parts) 3) (= (der-tag sigalg) #x30)
                   (= (der-tag (third parts)) #x03))
        (%fail "invalid certificate structure"))
      (when (= (logand (der-tag (nth i tc)) #xe0) #xa0)
        (setf version (1+ (%integer (first (%children (nth i tc))))) i (1+ i)))
      (let* ((serial (%integer (nth i tc))) (tbs-sigalg (nth (1+ i) tc))
             (issuer (nth (+ i 2) tc))
             (validity (nth (+ i 3) tc)) (subject (nth (+ i 4) tc)) (spki (nth (+ i 5) tc))
             (extensions nil))
        (unless (and tbs-sigalg (= (der-tag tbs-sigalg) #x30)
                     (equalp (der-raw tbs-sigalg) (der-raw sigalg)))
          (%fail "TBSCertificate and outer signature algorithms differ"))
        (dolist (extra (nthcdr (+ i 6) tc)) (when (= (der-tag extra) #xa3) (setf extensions (%parse-extensions extra))))
        (let ((bc (%find-ext extensions "2.5.29.19")) (ku (%find-ext extensions "2.5.29.15"))
              (eku (%find-ext extensions "2.5.29.37")) (san (%find-ext extensions "2.5.29.17"))
              (nc (%find-ext extensions "2.5.29.30")) (v (%children validity)))
          (make-x509-certificate :version version :serial-number serial :issuer (%name issuer)
            :subject (%name subject) :not-before (%time (first v)) :not-after (%time (second v))
            :public-key (%spki spki) :signature-algorithm (multiple-value-bind (o) (%algorithm sigalg) o)
            :tbs-signature-algorithm (multiple-value-bind (o) (%algorithm tbs-sigalg) o)
            :tbs-certificate (der-raw tbs)
            :signature (let ((value (der-content (third parts))))
                         (if (and (plusp (length value)) (zerop (aref value 0)))
                             (subseq value 1)
                             (%fail "certificate signature has unused bits")))
            :extensions extensions :basic-constraints (and bc (%basic-constraints (getf bc :value)))
            :key-usage (and ku (%key-usage (getf ku :value)))
            :extended-key-usage (and eku (mapcar #'%oid (%children (getf eku :value))))
            :subject-alternative-name (and san (%general-names (getf san :value)))
            :name-constraints (and nc (%name-constraints (getf nc :value) (getf nc :critical)))))))))

(defun parse-certificate-der (der) (%parse-certificate (%octets der)))
(defun parse-x509-certificate (input) (parse-certificate-der input))
(defun parse-certificate (input) (parse-certificate-der input))

(defun x509-rsa-public-key-modulus (key) (getf (x509-public-key-data key) :modulus))
(defun x509-rsa-public-key-exponent (key) (getf (x509-public-key-data key) :exponent))
(defun x509-ec-public-key-curve (key) (x509-public-key-parameters key))
(defun x509-ec-public-key-point (key) (x509-public-key-data key))
(defun x509-ed25519-public-key-point (key) (x509-public-key-data key))
